### ISSUE TITLE
Receive XOR option is broken

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#104]
Receive XOR option is broken
![image](https://github.com/sora-xor/sora-card-ios/assets/17094492/db7b5551-df8b-4cb5-b253-44e37a3543c1)
_Originally posted by @ra9mls in https://github.com/sora-xor/sora-card-ios/issues/97#issuecomment-1781722474_

**Comment by 2bogd** [comment]
No design in figma, decided to do as is in android (screen from main app: receive on selected address)
![receiveScreen](https://github.com/sora-xor/sora-card-ios/assets/99387689/a0938e43-175d-4096-b166-17d17546018c)

**Comment by Trezeguet1** [comment]
The case is repeated when there is not enough XOR on the balance for initial registration in Sora Card.

![telegram-cloud-photo-size-2-5357567507138990736-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/597af31b-2def-4358-a334-26fb130f00cd)

**Comment by Trezeguet1** [comment]
Verified on 3.7.0 (13) version from TF Soralution.

![telegram-cloud-photo-size-2-5359622112119214552-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/fc814411-05bb-425c-9e02-507b7b9d6f33)


![telegram-cloud-photo-size-2-5359622112119214551-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/2b0ddf52-0c28-403a-ac8b-ffa1812b6216)

**Comment by Trezeguet1** [comment]
Please delete from dialog screen the text  "**You can swap for XOR or buy with Euro**".

![image](https://github.com/sora-xor/sora-card-ios/assets/51509139/1c6fd129-4d9d-4b8f-a3c2-3062da666b10)

**Expected result:**

![telegram-cloud-photo-size-2-5361589945875156722-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/f7b7118d-ff77-41f5-8d93-60549de5b2c1)

**Comment by Trezeguet1** [comment]
![telegram-cloud-photo-size-2-5363881529970904480-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/a75c84bb-0609-453c-b36b-1e349864677a)
