### ISSUE TITLE
[Bug]: Card hub screen double opening during IBAN pending

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#105]
### Steps to reproduce

1. User in pending status
2. Approve user on PW
3. Tap on Sora Card button (or go from More menu)

### Actual behavior

Card Hub screen opens two times

https://github.com/sora-xor/sora-card-ios/assets/17094492/e95a7c11-84d6-46f5-81ee-bfb112983823

### Expected behavior

User sees Card Hub screen

### Environment

{"label"=>"Development"}

### OS version

iOS

**Comment by 2bogd** [comment]
builds: https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/view/tags/job/3.7.1/

**Comment by Trezeguet1** [comment]
Verified on 1.0. (259) develop version.
