### ISSUE TITLE
[Bug]: Support chat button is missing from Card details and Card hub screen

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#106]
### Steps to reproduce

1. User has a Approved status

### Actual behavior

User sees Card settings block without Telegram support button
![IMG_CDBEF09439F2-1](https://github.com/sora-xor/sora-card-ios/assets/17094492/3676be56-ce47-45ab-8707-89b10cc36040)
![image](https://github.com/sora-xor/sora-card-ios/assets/17094492/28ad41a5-b2f6-497b-8a79-21374866c955)

### Expected behavior

<img width="395" alt="Screenshot 2023-10-27 at 18 48 20" src="https://github.com/sora-xor/sora-card-ios/assets/17094492/1211b290-229e-42b6-bb09-9d98affd2c6e">

### Environment

{"label"=>"Development"}

### OS version

iOS

**Comment by Trezeguet1** [comment]
Verified on 3.8.4(7) Soralution version.
There is still no redirect to https://t.me/soracardofficial by tapping Support chat button.

![telegram-cloud-photo-size-2-5202008842559412570-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/2bec2918-0009-4ee1-ac29-a94da3dc29bb)

**Comment by 2bogd** [comment]
![IMG_5364](https://github.com/sora-xor/sora-card-ios/assets/99387689/c09168c1-3c07-4f06-8c73-27898dfbaa60)

**Comment by Trezeguet1** [comment]
Verified on 3.8.5(1) develop version.
