### ISSUE TITLE
[Bug]: [SORA Card] iOS - There is no pending status for the Sora card banner

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-ios#108]
### Preconditions

Complete sign up Sora card flow

![telegram-cloud-photo-size-2-5323774008669360878-y](https://github.com/sora-xor/sora-ios/assets/51509139/64d66135-608b-4756-8075-406c19ca7c37)

### Steps to reproduce

1. Approve documents in Admin panel 
2. Check SORA Card banner status -> Log out
3. Login another number for Sora card
4. Reject documents in Admin panel 
5. Check SORA Card banner status 
6. Repeat reject flow 4 times

### Actual behavior

There is no pending status for the Sora card banner. 
Either zero is shown or the text get SORA card when you re-login to the app.

<img width="327" alt="image" src="https://github.com/sora-xor/sora-ios/assets/51509139/3c70347c-3146-421a-af1d-e49931161f81">

![telegram-cloud-photo-size-2-5323665981651933452-y](https://github.com/sora-xor/sora-ios/assets/51509139/346ebd62-bab8-4762-be2c-8edd0a3c1457)

### Expected behavior

Shimmers and pending status should be displayed while the SORA card status is changing.

https://www.figma.com/file/Rqm3Y2XAq3pg0zfProoaqe/%F0%9F%8E%A8-SORA-Wallet-(In-Design)?type=design&node-id=4168-3842&mode=design&t=5NtR4eVjKPF4IzHI-0

<img width="745" alt="Screenshot 2023-10-30 at 20 36 20" src="https://github.com/sora-xor/sora-ios/assets/51509139/26de1298-51eb-43cc-81f1-0ea723caa0d4">

### Environment

{"label"=>"Development"}

### OS version

16.2

### Additional context

Sora Dev 1.0 (236) for iOS version

![telegram-cloud-photo-size-2-5323665981651933330-y](https://github.com/sora-xor/sora-ios/assets/51509139/1b933fc1-3ca1-412b-b03f-dc23300b7f1c)

**Comment by 2bogd** [comment]
@spitsynval looks like we have inconsistency in design for case when no balance to display
need some clarifications

<img width="502" alt="Снимок экрана 2023-11-10 в 15 02 24" src="https://github.com/sora-xor/sora-card-ios/assets/99387689/c232f24e-a19f-4f03-8cd1-12cc02e1e39b">
<img width="435" alt="Снимок экрана 2023-11-10 в 15 02 50" src="https://github.com/sora-xor/sora-card-ios/assets/99387689/f510aa5a-4c8b-4683-bf29-ddb42a8bf8ce">

**Comment by 2bogd** [comment]
builds: https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/view/tags/job/3.7.1/

**Comment by Trezeguet1** [comment]
Verified on 1.0. (259) develop version.

We need add the case when no balance to display.

<img width="477" alt="Screenshot 2023-11-27 at 13 25 33" src="https://github.com/sora-xor/sora-card-ios/assets/51509139/05b08f3a-f8b2-48ed-873a-a57b59d8ed2c">

**Comment by 2bogd** [comment]
Small updates 

Screen 1 is for case when IBAN is not exist yet  
Screen 2 is for case when IBAN is exist but having network problem for loading it

1 <img width="502" alt="Снимок экрана 2023-11-10 в 15 02 24" src="https://github.com/sora-xor/sora-card-ios/assets/99387689/c232f24e-a19f-4f03-8cd1-12cc02e1e39b">
2 <img width="435" alt="Снимок экрана 2023-11-10 в 15 02 50" src="https://github.com/sora-xor/sora-card-ios/assets/99387689/f510aa5a-4c8b-4683-bf29-ddb42a8bf8ce">

@spitsynval

**Comment by Trezeguet1** [comment]
Verified on 3.8.3 (21) version.
