### ISSUE TITLE
Update Not enough XOR screen

### ISSUE THREAD

**Issue by 2bogd** [sora-xor/sora-card-ios#109]
Need update KYC description screen to Not enough XOR screen from figma
Disign: https://www.figma.com/file/5kaHWqH73Ekez7RVOpH36g/%E2%9C%85-SORA-Wallet-(on-Prod)?type=design&node-id=13169%3A6594&mode=design&t=nrKsV4g2BDxK0Lc3-1

![simulator_screenshot_420CBEB5-8733-476C-A66E-124364C16A0E](https://github.com/sora-xor/sora-card-ios/assets/99387689/6ffaca0f-da65-4d88-a92f-939c3a9ceafe)
<img width="285" alt="Снимок экрана 2023-10-31 в 13 54 29" src="https://github.com/sora-xor/sora-card-ios/assets/99387689/233221c4-b893-4bca-95d7-0087a8c1d81f">

**Comment by 2bogd** [comment]
builds: https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/view/tags/job/3.7.1/

**Comment by Trezeguet1** [comment]
Verified on 1.0. (259) develop version.
The issue is still repro.
Merge fix to develop from builds: https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/view/tags/job/3.7.1/

**Comment by 2bogd** [comment]
will update SCard dependency on next release branch

**Comment by Trezeguet1** [comment]
Verified on 3.8.3(9) Soralution version.

Design:
https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=7385-267&mode=design&t=9jAu76Sd7z7lQjoc-0

There is no text below the Get more XOR:

"You can swap for XOR or buy with card".

![telegram-cloud-photo-size-2-5355306039353924094-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/dc573cf3-0ff5-426e-af24-24aedabc0956)

**Comment by Trezeguet1** [comment]
Verified on 3.8.4.0 Soralution version.

Add please "Your phone number: +358 50 633 12 89" field.

Because it would be useful to see, otherwise the user entering a number with 0 thinks that he entered it, but in fact we cut it off.

![telegram-cloud-photo-size-2-5201834166239487042-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/d58d1c5a-28ae-4609-b265-7747b8fa0d2d)

**Comment by Trezeguet1** [comment]
The feature task will be designed by Boris for the next sprint.
