### ISSUE TITLE
[Bug]: Dark theme of Sora Card has UI problems

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#111]
### Steps to reproduce

1. Open More menu
2. System settings
3. Dark theme switch on
4. Go to main screen
5. Tap Sora Card button

### Actual behavior

https://github.com/sora-xor/sora-card-ios/assets/17094492/186d640b-b9bc-4a7a-97ac-cd3b1865bcd8

https://github.com/sora-xor/sora-card-ios/assets/17094492/7b8af787-c15c-4142-ab9d-9b0beb2aeb5e

### Expected behavior

-

### Environment

{"label"=>"Development"}

### OS version

iOS

**Comment by Tieumsan** [comment]
@bgodlin @ra9mls is it fixed ?
Please either close the task if it has been fixed or update the release it will be included in.

**Comment by 2bogd** [comment]
Build: https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/view/tags/job/3.7.0/12/console

**Comment by Trezeguet1** [comment]
Verified on 3.7.0 (13) version.

![telegram-cloud-photo-size-2-5361589945875156765-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/ea5167fc-a837-4509-9b75-69e3fa44bc85)

![telegram-cloud-photo-size-2-5361589945875156766-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/95ef1507-8d0d-42cc-92fe-5e5f8f49f8a2)

**Comment by ra9mls** [comment]
I close it and create new issue for the wrong dialog.
https://github.com/sora-xor/sora-card-ios/issues/117
