### ISSUE TITLE
[Bug]: iOS - Incorrect Card issuance screen for Not enough XOR case

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-ios#115]
### Preconditions

SORA Card banner appears

### Steps to reproduce

1. Import wallet without XOR
2. Tan SORA Card banner

### Actual behavior

Incorrect Card issuance screen for Not enough XOR case. There is no Log out option looks like as in design.

![telegram-cloud-photo-size-2-5361589945875156536-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/70156e51-99c0-4438-addb-4704ef68ce23)

### Expected behavior

There should be correct Card issuance screen for Not enough XOR case as in design.
The Log out option should be presented.

![telegram-cloud-photo-size-2-5361589945875156589-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/012cb55d-162b-49f5-9d64-a651b026157f)

### Environment

{"label"=>"Development"}

### OS version

16.2

### Additional context

Design:
https://www.figma.com/file/5kaHWqH73Ekez7RVOpH36g/%E2%9C%85-SORA-Wallet-(on-Prod)?type=design&node-id=13169-6595&mode=design&t=cBNst6TTaRGO8LqR-4

**Comment by 2bogd** [comment]
duplication of https://github.com/sora-xor/sora-card-ios/issues/109

**Comment by Trezeguet1** [comment]
Verified on 1.0. (259) develop version.
The issue is still repro.

![telegram-cloud-photo-size-2-5407120228460122664-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/d2304bbb-f7ec-4f5e-a3c3-8d270ad0fd73)

![telegram-cloud-photo-size-2-5407120228460122665-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/ac04dba6-9e90-49b6-a078-dbf5e72bdedc)

**Comment by Trezeguet1** [comment]
Merge fix to develop from builds: https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/view/tags/job/3.7.1/
