### ISSUE TITLE
[Bug]: iOS - The application freezes and crashes when opening Card hub

### ISSUE THREAD

**Issue by pg-vlad** [sora-xor/sora-card-ios#122]
### Preconditions

Get the user IBAN

### Steps to reproduce

1. Sora Card log in
2. Go to Sora Card hub (click to 0 €)

### Actual behavior

The application freezes and crashes when opening Card hub

https://github.com/sora-xor/sora-card-ios/assets/55486343/91e7f84b-5da3-4aa6-9849-9d611e11d879

### Expected behavior

The application does not  freeze

### Environment

{"label"=>"Stage"}

### OS version

iOS

### Additional context

Soralution 3.7.0 (22)
iPhone 14 Pro Max iOS 16.3
phoneApproved =38267873350

**Comment by 2bogd** [comment]
@pg-vlad  While nothing can be reproduced, more specific steps or a specific environment are needed.

**Comment by Trezeguet1** [comment]
I still can't reproduce this bug using the current steps.

**Comment by 2bogd** [comment]
@springgale did found interesting fact, if you change zoom in device settings if will fix the crash

symptoms are really similar to this but starts from version of OS 16 https://developer.apple.com/forums/thread/737931
The app freez caused by endless cycle ios Foundation

**Comment by Trezeguet1** [comment]
There will be no more crashes on version on 1.0(259) develop.
