### ISSUE TITLE
[Bug]: iOS - Country search doesn't work in languages other than English

### ISSUE THREAD

**Issue by pg-vlad** [sora-xor/sora-card-ios#123]
### Preconditions

Install turkish localization on the device

### Steps to reproduce

1. Sora Card Sign In
2. Open country select list
3. insert the country in turkish language 

https://github.com/sora-xor/sora-card-ios/assets/55486343/477a1b1b-aeaa-471d-b916-952a58f50432

### Actual behavior

The search cannot find the country in the list in Turkish

### Expected behavior

the user can find the country in list in any language

### Environment

{"label"=>"Stage"}

### OS version

iOS

**Comment by Trezeguet1** [comment]
Verified on 3.8.3 (8) version.

The problem is still relevant for Turkey as I observe.

![image](https://github.com/sora-xor/sora-card-ios/assets/51509139/1d97aa1d-3737-4f62-a17e-cce0174934b8)

**Comment by Trezeguet1** [comment]
Verified on 3.8.4(7) Soralution version.

![telegram-cloud-photo-size-2-5202008842559412551-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/d37fe3da-88da-4976-b616-b109db7c2277)
