### ISSUE TITLE
[Bug]: Sora card balance cuts the cents

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#127]
### Preconditions

User has a balance on Sora card account (100.40 euro)

### Steps to reproduce

1. Login under the phone who has a balance on Sora card 
2. Tap on Sora card button 

### Actual behavior

User sees 100 euro balance

### Expected behavior

User sees 100.40 euro

### Environment

{"label"=>"Stage"}

### OS version

iOS

**Comment by Trezeguet1** [comment]
Verified on 3.8.3 (8) version.

![telegram-cloud-photo-size-2-5346164549356737470-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/96ff7ff9-80e7-46f5-a72d-7a2dbba368f9)
