### ISSUE TITLE
[Tech]: Review the Sora card status handling mechanism

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#128]
### Problem statement

When I launch It displayed "Get SORA Card" and when I clicked (it took 2-3 seconds to open) I got the first step to retry submitting my application. And couldn't get back to the verification status page.
https://t.me/c/1733547496/5520/6472

### Definition of Done

When app starts user gets the Sora card status immediately

**Comment by Trezeguet1** [comment]
Verified on 3.8.3 (8) version.
We immediately see the received status of the Sora card when we launch the application.
 
https://github.com/sora-xor/sora-card-ios/assets/51509139/6bbde54c-aa50-4b4e-92bd-a104c6222662
