### ISSUE TITLE
[Bug]: iOS - The loader is not immediately displayed when going to SORA Card Hub

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-ios#134]
### Preconditions

- Bad internet connection
- Pending status of SORA Card

### Steps to reproduce

1. Open SORA Card Hub
2. Wait until data is loaded

### Actual behavior

The loader is not immediately displayed when going to SORA Card Hub.

https://github.com/sora-xor/sora-card-ios/assets/51509139/79cdbe38-f47e-4015-863f-3b77bd7d8818

### Expected behavior

The loader should always be shown while data is loading when going to SORA Card Hub.

### Environment

{"label"=>"Stage"}

### OS version

17.2.1 

### Additional context

Soralution 3.8.3(3) version

**Comment by Trezeguet1** [comment]
Added to next release scope.

**Comment by Trezeguet1** [comment]
We need to add loader before Log in SORA Card.

**Comment by Trezeguet1** [comment]
Verified on 3.8.4(7) Soralution version.

The loader is still not visible on the dark and light themes when we select the details of the SORA Card hub.

![telegram-cloud-photo-size-2-5197261503537994358-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/65e61c39-49e9-4d2b-b929-4c34a7d43c2c)

**Comment by 2bogd** [comment]
build Hash: 7deaf5ed

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 3.8.6 (2) version.
