### ISSUE TITLE
[Bug]: iOS - [Blocked] It's giving me an error and I can't request the card

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-ios#138]
### Preconditions

Email is not confirmed yet

### Steps to reproduce

1. Tap on SORA Card Hub
2. Try to complete KYC flow

### Actual behavior

It's giving me an error and I can't request the card.

![telegram-cloud-photo-size-1-5008032567395461857-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/64baf2cf-ad30-488d-aefa-5e764debc22a)

### Expected behavior

Most likely the problem is in a language that does not support the sdk and it needs to be fixed.

### Environment

{"label"=>"Stage"}

### OS version

17.2.1 

### Additional context

Soralution 3.8.3(3) version

**Comment by 2bogd** [comment]
build 3.8.3 (7)

**Comment by Trezeguet1** [comment]
Verified on 3.8.3 (8) version.

We are waiting for the reCaptcha production keys from PW, Tjasa is informed.

![image](https://github.com/sora-xor/sora-card-ios/assets/51509139/71b5ab69-ecbb-4035-aab9-100b6b432228)

**Comment by Trezeguet1** [comment]
Verified on 3.8.3 (9) Soralution version.

The issue doesn't repro on Spanish language.

Production keys were just sent to @bogsdan and @arvifox.
