### ISSUE TITLE
[Bug]: iOS - An empty error is shown if the user interrupts the KYC process

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-ios#139]
### Preconditions

Email is not confirmed yet

### Steps to reproduce

1. Tap on SORA Card Hub
2. Try to complete KYC flow
3. Interrupt the KYC process

### Actual behavior

An empty error is shown in the new SDK if the user interrupts the KYC process.

![telegram-cloud-photo-size-2-5341619383035876285-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/44763377-0993-40a7-8c72-16a914969b2f)

### Expected behavior

It is necessary to add error text in the new SDK if the user interrupts the KYC process.

### Environment

{"label"=>"Stage"}

### OS version

17.2.1 

### Additional context

Soralution 3.8.3(3) version

**Comment by 2bogd** [comment]
build 3.8.3 (7)

**Comment by Trezeguet1** [comment]
Verified on 3.8.3 (8) version.

![telegram-cloud-photo-size-2-5345854865034826652-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/05173e25-faf0-4f0b-8978-f13f2132e408)
