### ISSUE TITLE
[Bug]: iOS - Crash happens during email verification for SORA Card

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-ios#140]
### Preconditions

Email is not confirmed yet

### Steps to reproduce

1. Tap on SORA Card Hub
2. Go to the verification email screen
3. Open email and confirm via message
4. Go back to the app

### Actual behavior

 Crash happens during email verification for SORA Card.
 
 
![telegram-cloud-photo-size-2-5341619383035876413-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/556597c6-b493-488a-a29b-048629d31a96)

![telegram-cloud-photo-size-2-5341619383035876544-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/8f4dc710-3f9d-4993-b57c-c5db2d17df20)

### Expected behavior

There should be no crashes during email verification for SORA Card.

### Environment

{"label"=>"Stage"}

### OS version

17.2.1 

### Additional context

Soralution 3.8.3(3) version

**Comment by 2bogd** [comment]
Not sure, looks like it is not card  related
https://console.firebase.google.com/u/1/project/sora-passport-id/crashlytics/app/ios:co.jp.soramitsu.sora.test/issues/69b33dbfbf1b7e08281898692ab33b77?time=last-seven-days&types=crash&sessionEventKey=2f66fb9891cb4e2fa2b410493b773656_1911373581737544058

**Comment by 2bogd** [comment]
build 3.8.3 (7)

**Comment by Trezeguet1** [comment]
Verified on 3.8.3 (8) version.
The crash is not related to SORA Card flow.
