### ISSUE TITLE
[Bug]: iOS - The text on the Re-send button is not visible for the dark theme

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-ios#141]
### Preconditions

Email is not confirmed yet

### Steps to reproduce

1. Tap on SORA Card Hub
2. Go to the verification email screen

### Actual behavior

The text on the "Re-send" button is not visible for the dark theme on "Verify your email" screen.

![telegram-cloud-photo-size-2-5341619383035876523-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/e3cdd85d-f6a9-4796-b1a5-ab3681155999)

### Expected behavior

Need to fix the layers on the Re-send button for the dark theme on Verify your email screen.

### Environment

{"label"=>"Stage"}

### OS version

17.2.1 

### Additional context

Soralution 3.8.3(3) version

**Comment by 2bogd** [comment]
build 3.8.3 (7)

**Comment by Trezeguet1** [comment]
Verified on 3.8.3 (7) version.

Added to next release scope.

**Comment by Trezeguet1** [comment]
Verified on 3.8.3 (8) version.

![telegram-cloud-photo-size-2-5345854865034826833-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/799836a1-d6fd-43c6-8331-6fb52e4facf5)
