### ISSUE TITLE
[Bug]: No phone number or email error after reject status

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#142]
### Preconditions

User passed the flow on this device and was rejected 
User has rejected phone

### Steps to reproduce

1. Tap retry button

### Actual behavior

User sees the error message
![image](https://github.com/sora-xor/sora-card-ios/assets/17094492/9ac53dad-8d05-4845-9f5f-c857fa814a76)

### Expected behavior

User sees retry flow

### Environment

{"label"=>"Stage"}

### OS version

iOS

**Comment by 2bogd** [comment]
build 3.8.3 (7)
