### ISSUE TITLE
[Bug]: Update app alert on dark mode looks bad

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#143]
### Preconditions

User has old version of the app
User uses Dark mode

### Steps to reproduce

1. Open the app

### Actual behavior

User sees alert: Please update the app to last version with light UI
![image](https://github.com/sora-xor/sora-card-ios/assets/17094492/2e4f270c-74ca-47b3-b657-dc96c00cc213)

### Expected behavior

User sees alert: Please update the app to last version with Dark UI

### Environment

{"label"=>"Production"}

### OS version

iOS

**Comment by Trezeguet1** [comment]
We need to ask for testing to install the next release version for a while in a dev environment on the backend and check it.
Currently in the application currentSDKVersion = "2.2.4".

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 3.8.6 (2) version.
