### ISSUE TITLE
[Bug]: iOS - A crash occurs if you cancel permissions during the KYC process

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-ios#144]
### Preconditions

Verification Status - None Status

### Steps to reproduce

1. Start KYC
2. Cancel access to the microphone or camera

### Actual behavior

An empty screen hangs and crashes all the time if you do not give access to the microphone or camera during KYC.

![telegram-cloud-photo-size-2-5398048450077119826-y](https://github.com/sora-xor/sora-ios/assets/51509139/3f1bded1-6f77-401d-aa94-d2974dd057cb)

![telegram-cloud-photo-size-2-5398048450077119827-y](https://github.com/sora-xor/sora-ios/assets/51509139/5f9bdf11-3089-4094-a701-a3769afb049f)

### Expected behavior

The KYC process should not be blocked by anything even if you do not give access to the microphone or camera.

### Environment

{"label"=>"Production"}

### OS version

17.2.1

### Additional context

Soralution 3.8.3 (21) version

**Comment by Trezeguet1** [comment]
Verified on 3.8.4(7) Soralution version.

Th issue is still repro.

![telegram-cloud-photo-size-2-5202008842559412497-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/992518d2-9fdd-403a-9847-832ccd3c4492)

![telegram-cloud-photo-size-2-5202008842559412498-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/b7ac5a63-05a4-4a61-acbc-4d3b6b0244ae)

**Comment by 2bogd** [comment]
Can not reproduce, some specific steps or environment details are needed

https://github.com/sora-xor/sora-card-ios/assets/99387689/c8316812-0bcd-40d4-a9d4-7b029e498a5c


https://github.com/sora-xor/sora-card-ios/assets/99387689/59bbc21f-cc47-4246-b6cd-566289f2e6fc

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 3.8.6 (2) version.

![telegram-cloud-photo-size-2-5377758234296834143-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/99094cd5-e714-43c6-8e2e-ba055c36b1dd)

![telegram-cloud-photo-size-2-5377758234296834144-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/0c96b8aa-1cb9-45a6-b7bc-04c937216322)
