### ISSUE TITLE
[Tech]: Update PW SDK

### ISSUE THREAD

**Issue by 2bogd** [sora-xor/sora-card-ios#146]
### Problem statement

New versions of PW SDKs are published 

### Description

OAuth has that change we were talking about to prevent API calls when user is logged out. 
KYC now allows EndpointUrl both with "/" at the end or without, and SumSub SDK is updated to the new version that has some good fixes:
- Added an ability to capture documents automatically at Identity steps
- Improved quality of the video recording at Video Selfie step
- Fix for the false error reporting when the sdk is opened then closed right away
- Fix in order to allow re-uploading of a once uploaded document after the cancellation on Preview Screen
- Fix for a possible crash under iOS 17+ when the sdk fails to make a preview for a pdf file selected

pod 'PayWingsOAuthSDK', '2.0.2'
pod 'PayWingsKycSDK', '1.0.1'
pod 'IdensicMobileSDK', :http => 'https://github.com/paywings/PayWingsOnboardingKycSDK-iOS-IdensicMobile/archive/v2.2.4.tar.gz'

### Acceptance Criteria

-

### Definition of Done

-

**Comment by Trezeguet1** [comment]
Verified on 3.8.4(7) Soralution version.
