### ISSUE TITLE
iOS - Display SORA Card IBAN Balance on Main Menu

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-ios#15]

**Comment by 2bogd** [comment]
Build: dev 166
Without loading / error states.

**Comment by ra9mls** [comment]
Balance is absent on the main screen
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVVnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2f5e754bde7fe7d5b49985994b38b9744b6ef8f/image.png)
