### ISSUE TITLE
[Bug]: iOS - Stable freeze on card details after receiving Success KYC status

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-ios#153]
### Preconditions

The Success KYC status have done

![telegram-cloud-photo-size-2-5381989992559139064-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/a892432b-df26-40a0-b28f-5cdc4e548bd8)

### Steps to reproduce

1. Tap on Get SORA Card button

### Actual behavior

 Stable freeze on card details after receiving Success KYC status.
There's a zero balance and it won't load, so I think that's the problem.

![telegram-cloud-photo-size-2-5381989992559139063-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/b4e998ab-88fb-4efa-a978-846017d0cb34)

https://github.com/sora-xor/sora-card-ios/assets/51509139/2de680e2-4db7-45ce-bb1d-15d736344948

### Expected behavior

There should be no freezes or errors on card details after receiving Success KYC status.

### Environment

{"label"=>"Development"}

### OS version

17.4.1

### Additional context

Sora Dev 3.8.6 (2) version

**Comment by 2bogd** [comment]
Looks like inconsistent user state on MW

`
200 'https://backend.dev.sora-card.tachi.soramitsu.co.jp/kyc-attempt-count'
{"total":2,"completed":0,"successful":0,"retry":0,"rejected":0,"total_free_attempts":4,"free_attempts_left":4,"free_attempt":true}

200 'https://backend.dev.sora-card.tachi.soramitsu.co.jp/kyc-last-status'
{"kyc_id":"d4b5d8e4-a1fe-4ca5-b7f4-a148e3f9f33f","person_id":"6dc1e221-eb07-47ab-9e6e-f80bd5fd847f","user_reference_number":"83Ho8Jde","reference_id":"a660f764-3106-4f5f-a943-a0dad9e05878","kyc_status":"Failed","verification_status":"None","iban_status":"None","card_status":"None","additional_description":"User cancelled KYC process.","rejection_reasons":null,"update_time":1708963546}
`

**Comment by Trezeguet1** [comment]
Fixed. Issue is repeated only in one case out of 5 mobile devices.
Verified on Soralution version.
