### ISSUE TITLE
iOS - Display Card Balance in the SORA Card Hub

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-ios#16]
As a <ins>SORA Card user</ins> I want to <ins>have an overview of my SORA Card account within the crypto wallet</ins> so that <ins>I can easily access my fiat wallet from my crypto wallet</ins>.

Aha! Link: https://soramitsucoltd.aha.io/features/SORANEO-671

**Comment by 2bogd** [comment]
Build: dev 166
Without loading / error states.
