### ISSUE TITLE
[Bug]: [SC] KYC notification deserialization error occurs when calling IBAN webhook

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-ios#161]
### Preconditions

- Copy KYC data on Dashboard: https://kyc-test.soracard.com/Dashboard/admin/WhitelabelKycList

### Steps to reproduce

1. Use Postman collection and Fill in "ReferenceID" and "PersonID for body of request
2. Send POST request to https://kyc-test.soracard.com/whitelabel/CreatePersonIban 
3. Check middleware logs on Dashboard 

https://opensearch.soramitsu.co.jp/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-10h,to:now))&_a=(columns:!(logdata),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e3bd6ab0-f3e7-11ed-8ed8-b7c4a5d2f81f,key:fields.logtype,negate:!f,params:(query:sora-card),type:phrase),query:(match_phrase:(fields.logtype:sora-card)))),index:'7c942030-5184-11ef-8ed8-b7c4a5d2f81f',interval:auto,query:(language:kuery,query:''),sort:!())

### Actual behavior

KYC notification deserialization error occurs when calling IBAN webhook.
IBAN get stuck in pending status - we don't receive the webhook for account.

### Expected behavior

The IBAN should be generated and received after setting the KYC completion status to “Successful” in the KYC dashboard.

### Environment

{"label"=>"Stage"}

### OS version

17.4.1

### Additional context

To proceed with testing on the staging environment, please follow the instructions outlined in this message https://t.me/c/1869740055/912. Specifically, you will need to call the CreatePersonIban method.

You should have received a preconfigured Postman collection via email, which includes the endpoint and credentials. The only parameters you need to provide are the KYC and Person reference details. To continue, access the dashboard, copy the KYC-related parameters, and use them to call the method in Postman. Once done, you should receive the IBAN issuing webhook.

**Comment by wer1st** [comment]
We get the message:

**Comment by wer1st** [comment]
We get the message:
```json
{
    "Data": {
        "KycID": "cff7130a-58ee-4898-9338-bc4790b076b6",
        "PersonID": "5f361545-747b-4e80-9aaf-85aadeda008c",
        "ReferenceNumber": null,
        "ReferenceID": null,
        "KycStatus": "Successful",
        "VerificationStatus": "Accepted",
        "IbanStatus": "Pending",
        "CardStatus": "None",
        "AdditionalDescription": null
    },
    "WhitelabelID": "e9598beb-af3e-4ac4-ad53-e7159da242aa",
    "WhitelabelAccountID": "b3228cad-8af4-4971-85da-49dbcff603de",
    "Type": "KYC"
}
```

`ReferenceNumber` cannot be null.
"ReferenceNumber" is a single way to bind received "PersonID" with stored "UserID".
In other words, without "ReferenceNumber" value, we cannot identify the user to whom the notification is intended.
It is a bug of Paywings.

**Comment by wer1st** [comment]
Paywings informed us that we can ignore messages with `ReferenceNumber = null`

**Comment by wer1st** [comment]
PR: https://github.com/soramitsu/sora-card-backend/pull/559

**Comment by Trezeguet1** [comment]
Verified

![Image](https://github.com/user-attachments/assets/0565789a-93ed-4a32-a74a-6f8cd1e97cac)
