### ISSUE TITLE
[Bug]: Bad request - Buy XOR token is still available via disabled button

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/sora-card-ios#163]
### Preconditions

![telegram-cloud-photo-size-2-5271605510531052598-y](https://github.com/user-attachments/assets/aec2f8c1-142b-47bc-acd0-50dda96bc914)

### Steps to reproduce

![telegram-cloud-photo-size-2-5271605510531052599-y](https://github.com/user-attachments/assets/dd5434eb-4920-49d5-a13f-d2dbdc24d786)

### Actual behavior

Buy XOR token is still available via the disabled button on the main screen.
Also a bad request error occurs when calling onboarding.

### Expected behavior

We need to remove access to onboarding as this task is not yet ready for the iOS platform.

### Environment

{"label"=>"Development"}

### OS version

17.7

**Comment by Viscount88** [comment]
Doesn't actual anymore. Feature is backed.
