### ISSUE TITLE
iOS - Buy fiat with XOR (Gatehub)

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-ios#20]
As a SORA Card user I want to buy fiat currency with my crypto within the wallet so that I can trade in the Traditional Finance economy seamlessly.

<ins>Exchanges integration:</ins>

- X1
- Gatehub

Aha! Link: https://soramitsucoltd.aha.io/features/SORANEO-669

**Comment by Trezeguet1** [comment]
such a task for the iOS platform developer has already been created in Jira
closing as a duplicate
