### ISSUE TITLE
[Tech]: Update KYC SDK

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-ios#28]
### Problem statement

We need to update the KYC SDK to version 5.1.9

### Definition of Done

- [x] SDK updated

**Comment by 2bogd** [comment]
just published v5.1.12 to cocoapods, will be available soon, documentation will be updated a bit later but just to let you know. No changes in implementation, just expanded language options for accounts that use SumSub: no language validation by the SDK, any language is passed to SumSub (default/fallback is english). If no language is specified at SDK initiation, device settings are used. Here is the list of supported languages: https://developers.sumsub.com/faq/#what-languages-does-sdk-support
