### ISSUE TITLE
[Bug]: iOS. Sora app translations depends on device language

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#37]
### Preconditions

User has already pass the flow

Set up English language in the app 

Set up Russian language in Device settings

### Steps to reproduce

Open sora card flow with +123456782273

### Actual behavior

User sees part of the text on Russian
![29db5d4e-da3b-4bbc-a35e-16b935cff7bf](https://github.com/sora-xor/sora-card-ios/assets/17094492/f9f0d54b-686a-4918-843e-c9986c3a8d17)

### Expected behavior

User sees all with appropriate translation

### Environment

{"label"=>"Development"}

**Comment by ra9mls** [comment]
Problem is still reproduced. Device has a Rus lang, the app has a Eng lang.
![IMG_0755.PNG](https://images.zenhubusercontent.com/62bbde011ca04a42bf2c5247/55501c71-4a4e-45f5-a1d9-6c07b9971c19)![IMG_0754.PNG](https://images.zenhubusercontent.com/62bbde011ca04a42bf2c5247/0a6e6549-9304-40b3-b21f-afabf66ed857)![IMG_0753.jpg](https://images.zenhubusercontent.com/62bbde011ca04a42bf2c5247/369c19e3-3469-4a28-99c1-3d21dc9e910c)

**Comment by OlgaSamorodnova** [comment]
The problem still remains in 2 places (back button is in Russian on all screens)
![photo_2023-07-14 11 44 11](https://github.com/sora-xor/sora-card-ios/assets/118749608/a1dfad89-91d9-4aef-b15d-c181820325d8)
![IMG_7854](https://github.com/sora-xor/sora-card-ios/assets/118749608/9aafbae9-5712-4717-88ff-d14499730b0e)

**Comment by OlgaSamorodnova** [comment]
Back button is still in Russian on most of the screens. It's not the problem of 1 certain screen, but all of them.

**Comment by 2bogd** [comment]
Going to hide back button title on all screens
