### ISSUE TITLE
[Feature]: Change the email changing method for iOS

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#40]
### As a

User I want to have opportunity to change Email before activation

### I want to

Change email right after OTP code check

### So that

We should use another method for it

**Comment by ra9mls** [comment]
![image.png](https://images.zenhubusercontent.com/62bbde011ca04a42bf2c5247/80c8ef3f-ebc8-4f5e-8b8c-fb8c2d6aae6e)
![Screenshot 2023-07-12 at 14.12.46.png](https://images.zenhubusercontent.com/62bbde011ca04a42bf2c5247/df6cc41a-156d-4a56-a267-5daca128038c)

**Comment by ra9mls** [comment]
Change Email doesn't work for now. 
It sends to the same email.

**Comment by 2bogd** [comment]
PW do not send emails for each time, not lear 
Build 89
