### ISSUE TITLE
[Bug]: The “Send SMS code” button is not blocked after clicking several times

### ISSUE THREAD

**Issue by pg-vlad** [sora-xor/sora-card-ios#41]
### Preconditions

Soralution iOS

### Steps to reproduce

1. Get Sora Card Flow
2. Enter phone number
3. Click to “Send SMS code” button  several times 

### Actual behavior

 Screen with Input otp opens several times. The “Send SMS code” button is not blocked after clicking several times
 
 https://github.com/sora-xor/sora-card-ios/assets/55486343/94de123b-f81d-4761-a836-d5efa985057a

### Expected behavior

 The “Send SMS code” button is disabled after clicking the first time

### Environment

{"label"=>"Stage"}

**Comment by 2bogd** [comment]
Build 87
