### ISSUE TITLE
[Bug]: When user changes email during the registration process he still get emails on the old email

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#44]
### Steps to reproduce

1. Input the unregistered phone number
2. Input OTP code
3. Input Name, Surname
4. Input email A and proceed
5. Tap Change the email button
6. Input email B and proceed

### Actual behavior

User sees the second email on the email A

### Expected behavior

User sees new email on the email B

### Environment

{"label"=>"Development"}

**Comment by 2bogd** [comment]
not clear PW login after run request registerUser
Build 89

**Comment by 2bogd** [comment]
PW do not send magic link on some number format : +999... need to clearify limitations for phone numbers

**Comment by 2bogd** [comment]
Looks like it is fixed on PW side and working right now
