### ISSUE TITLE
iOS - Display IBAN

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-ios#49]
As a <ins>SORA Card owner</ins> I want to <ins>see my account IBAN</ins> so that <ins>I can share it to receive money on it</ins>.

**IBAN Card**
**Design**: https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1872-10297&mode=design&t=T0MFEg0U4SNF13CE-0

**Comment by 2bogd** [comment]
https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/job/develop/116/

**Comment by ra9mls** [comment]
After successful aprove, user can't receive IBAN from the backend during 5-10 min. We need to show appropriate text or icon. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTBrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e42b458bbeb0acb0be51984df63a8bf7a9dcec44/image.png)

**Comment by 2bogd** [comment]
wrong task (requirements have changed, and we need to take account of demeter balance as well.)

**Comment by ra9mls** [comment]
Need to fix spacings between buttons.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWRiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--87d1b1b73e51aeea48cf3313fb76a6af3c3a59bc/image.png)
And and "Exchange" is truncated
