### ISSUE TITLE
iOS - UI for SORA Card card

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-ios#50]
Add the SORA Card card to provide an appealing enough SORA Card hub.<br/>

Only implement the UI for the SORA Card card:

- SORA Card image
- Greyed _Show details_ button
- Text (precise what to display instead of the amount)
- Buttons _Top up/Transfer/Exchange/Freeze_ buttons are disabled and greyed out

<br/> **Design** : https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1872-10297&mode=design&t=T0MFEg0U4SNF13CE-0

**Comment by 2bogd** [comment]
[dev https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/job/develop/111/](https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/job/develop/111/)

**Comment by 2bogd** [comment]
fix scrolling for small devices https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/job/develop/116/

**Comment by ra9mls** [comment]
Please fix small UI issues:
Very hard to Close this screen by swipe down
Space between SCard banner too much
IBAN details should have a icon
Log out of SORA Card text
Buttons should be in disabled state
1. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbE1YIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--63dca9f3e70b05ed486af38e25d9ff22087462f8/image.png)
2. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGdYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d71f521af31172d3c9394e2e63320294b0ac0f55/IMG_ACDB0D7921A6-1.jpeg)

**Comment by ra9mls** [comment]
Different paddings on devices
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1JQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b966617ade1899696df3a30be4d8df0b21daa6d1/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2RQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4fe2c3125e93d06b1bd2a94de7fe604f98eae9fe/image.png)

**Comment by 2bogd** [comment]
Fix for offsets on pro max devices https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/job/3.3.0/10
