### ISSUE TITLE
[Bug]: Wrong phone registering when user gets back from OTP step

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#58]
### Steps to reproduce

1. Input number1
2. Tap Back button
3. Change the number to number2
4. Input test OTP

https://github.com/sora-xor/sora-card-ios/assets/17094492/7c254921-e410-44b1-b680-eeb7262a30e8

### Actual behavior

User starts to register with number1
<img width="731" alt="Screenshot 2023-07-31 at 16 23 32" src="https://github.com/sora-xor/sora-card-ios/assets/17094492/0c150dae-19c0-4d33-bfa8-4971f92d5184">

### Expected behavior

User registered with number2

### Environment

{"label"=>"Development"}

### OS version

iOS

**Comment by ra9mls** [comment]
Cloned link from andriod https://github.com/sora-xor/sora-card-android/issues/64

**Comment by ra9mls** [comment]
Current realisation to be improved in the next releases.

**Comment by bgodlin** [comment]
@ra9mls Has this problem truly been fixed? It appears that the cloned issue remains unresolved. If this particular issue hasn't been resolved, kindly think of reopening it.
