### ISSUE TITLE
[Bug]: Restrict input characters to phone mask and OTP mask

### ISSUE THREAD

**Issue by pg-vlad** [sora-xor/sora-card-ios#59]
### Steps to reproduce

**Steps to reproduce**
Paste any characters in phone/OTP mask

### Actual behavior

Character are available for input

![characters_phonemask](https://github.com/sora-xor/sora-card-ios/assets/55486343/9c172497-3e2d-476c-9ee4-0ba24863de50)

![characters_otp](https://github.com/sora-xor/sora-card-ios/assets/55486343/f99a0d11-a272-4641-b125-a8de9da560a6)

### Expected behavior

Only digits are available for input.  characters are not available for input.

### Environment

{"label"=>"Stage"}

### OS version

iOS

**Comment by 2bogd** [comment]
will add local check with regex: `[0-9]{4,6}$` and error message: Wrong format!
