### ISSUE TITLE
[Tech]: Remove option to change receiving address in X1 widget

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-ios#60]
### Problem statement

Currently users can choose whether to send the XOR they buy through the X1 widget to their SOR address (external) or to the X1 address. 
To avoid any confusion, we should remove the option to send funds to the X1 address and only allow to send funds to the SORA address. 

### Definition of Done

- [ ] Option to change receiving address disabled

### Requirements

@bgodlin to complete

**Comment by bgodlin** [comment]
@Tieumsan I transfered the contents to the parent issue. Kindly eliminate the duplicate content from this issue, as I am unable to perform this action
