### ISSUE TITLE
[Bug]: Calculate staked balance for required XOR amount

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#62]
### Preconditions

User has more than 100 euro in XOR staked balance

### Steps to reproduce

1. Start registration flow
2. Register phone number
3. Approve email

### Actual behavior

User sees not enough xor balance to start registration process

### Expected behavior

User sees enough xor balance

### Environment

{"label"=>"Production"}

**Comment by 2bogd** [comment]
doc needed, we have this balances, it is not clear what to use 
![image](https://github.com/sora-xor/sora-card-ios/assets/99387689/60d6052e-d7ea-421b-a7ae-a761a665043e)

**Comment by 2bogd** [comment]
@bgodlin

**Comment by bgodlin** [comment]
@ra9mls could you offer additional context regarding the specific staking mechanism being used in the provided example?

**Comment by bgodlin** [comment]
Will be solved as part of https://github.com/sora-xor/sora-card-ios/issues/65

**Comment by bgodlin** [comment]
@ra9mls @2bogd please review https://github.com/sora-xor/sora-card/issues/60

**Comment by 2bogd** [comment]
On test env:
https://github.com/sora-xor/sora-card-ios/assets/99387689/ce247bc7-1f06-4c2c-b405-bf22cfb7ddfe
