### ISSUE TITLE
[Bug]: User could input phone number without +

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#63]
### Steps to reproduce

1. Open the sora card flow
2. Input the phone number 
3. remove '+' symbol and change it with '0'

### Actual behavior

![image](https://github.com/sora-xor/sora-card-ios/assets/17094492/8c8d85dc-4d50-4fcc-b1dd-8c0ddfb4fe7c)

### Expected behavior

User can proceed the flow

### Environment

{"label"=>"Production"}

### OS version

iOS

**Comment by 2bogd** [comment]
@ra9mls error is on PW side

**Comment by 2bogd** [comment]
![image](https://github.com/sora-xor/sora-card-ios/assets/99387689/ff0fa392-245c-461e-98de-ba022dab7481)
can't reproduce on test env
