### ISSUE TITLE
iOS - Calculate amount of XOR for 2 free KYC attempts

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-ios#65]

**Comment by ra9mls** [comment]
Waiting the Demeter Staking calculation

**Comment by 2bogd** [comment]
requirements have changed, and we need to take account of demeter balance as well.

**Comment by 2bogd** [comment]
build https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/job/3.3.0/9/console

**Comment by ra9mls** [comment]
Native staking has a problem. Staked amount is doubled.
(SoraPassport.BalanceContext) $R0 = {
  free = 999.551691

  reserved = 0
  miscFrozen = 999.000000

  feeFrozen = 999.000000

  bonded = 999.000000

  redeemable = 0
  unbonding = 0
  price = 0
  priceChange = 0
}
totalXorBalance = balanceContext.total + balanceContext.frozen + balanceContext.bonded

It strange why we see staked balance like a bonded.

**Comment by ra9mls** [comment]
Still a bug with native sora staking.

**Comment by ra9mls** [comment]
Fixed on 24 build soralution
