### ISSUE TITLE
iOS - Add disclaimer on documents accepted for proof-of-address

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-ios#66]

**Comment by 2bogd** [comment]
Blocked by Localize (no translation). 
Key: https://app.lokalise.com/project/828171766350fbd5dd3c48.67230943/?view=multi&search=get.prepared.proof.address.description need to be updated on all languages before release 3.3.0.

**Comment by 2bogd** [comment]
https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/job/3.3.0/12

**Comment by ra9mls** [comment]
Can't see the disclaimer on soralution from 16 build.

**Comment by ra9mls** [comment]
Can't see the disclaimer on soralution from 24 build.

**Comment by ra9mls** [comment]
25 build is ok
