### ISSUE TITLE
[Bug]: iOS small improvements from design review 

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#69]
### Steps to reproduce

-

### Actual behavior

1. Add logout and Close button
![image](https://github.com/sora-xor/sora-card-ios/assets/17094492/206154d7-eba1-4708-b7f1-5e98ec8ee310)
2. Open phone and sms screens with keyboard 
![image](https://github.com/sora-xor/sora-card-ios/assets/17094492/823908a9-f5ce-4199-8c72-a91093a9e8ed)
![image](https://github.com/sora-xor/sora-card-ios/assets/17094492/e32b9aa9-4875-487e-bc78-e0e0f356cc10)
3. Fix Get SORA Card button
![image](https://github.com/sora-xor/sora-card-ios/assets/17094492/88cd3476-5e15-4735-8360-a4e54ba4fd7f)

### Expected behavior

-

### Environment

{"label"=>"Production"}

### OS version

iOS

**Comment by 2bogd** [comment]
https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/view/tags/job/3.3.0/19/
