### ISSUE TITLE
[Bug]: Fix changing Close button on Card status screen

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#70]
### Preconditions

User was rejected first time

### Steps to reproduce

1. Open Card details screen

### Actual behavior

During the loading Close button changes to Support
https://github.com/sora-xor/sora-card-ios/assets/17094492/4e8a94ee-4e4e-4a0f-94ec-9ed3a48560ac

### Expected behavior

User sees Support button during the loader works

### Environment

{"label"=>"Production"}

### OS version

iOS

**Comment by 2bogd** [comment]
https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/view/tags/job/3.3.0/19/
