### ISSUE TITLE
Enhanced Check of Free KYC Attempts

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card-ios#73]

**Comment by 2bogd** [comment]
https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/job/3.3.0/14/console

**Comment by 2bogd** [comment]
new changes in API

Changes in \kyc-attempt-count response JSON on dev:
renamed field free_attempts -> free_attempts_left
added field total_free_attempts that returns total free KYC attempts (4)
