### ISSUE TITLE
[Bug]: Double Card hub screen opening

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#76]
### Preconditions

User successfully passed the kyc

### Steps to reproduce

1. Tap on SCard button

### Actual behavior

Screen Card Hub opens twice
https://github.com/sora-xor/sora-card-ios/assets/17094492/26cee12c-bf66-4334-b400-4cad38abd2a7

### Expected behavior

Card Hub screen opens once

### Environment

{"label"=>"Development"}

### OS version

iOS

**Comment by 2bogd** [comment]
https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/job/3.3.0/12/
