### ISSUE TITLE
Fetch application and retry fees dynamically

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-ios#77]

**Comment by 2bogd** [comment]
Build 178

**Comment by ra9mls** [comment]
Build 187 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1FTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9186aa5e575e6cd376596e1cd8687146c49ff304/image.png)
