### ISSUE TITLE
 Improving UI for the transitional phase between Verified KYC and Provisioned IBAN

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card-ios#86]

**Comment by bgodlin** [comment]
https://github.com/sora-xor/sora-card/issues/99#issuecomment-1737452010

**Comment by bgodlin** [comment]
https://github.com/sora-xor/sora-card/issues/99#issuecomment-1764019824

**Comment by spitsynval** [comment]
https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=6016%3A3508&mode=design&t=8a4B7rRC509IHJv5-1

**Comment by 2bogd** [comment]
build https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/job/3.6.0/5/console

**Comment by ra9mls** [comment]
Blocked by https://github.com/sora-xor/sora-card-ios/issues/103
