### ISSUE TITLE
iOS - fix the posotion of the cards to the sheets

### ISSUE THREAD

**Issue by OlgaSamorodnova** [sora-xor/sora-card-ios#89]
Can we fix the position of the cards to the sheets ?
To avoid this strange UX where there is 2 scrolling items (the card and the underlying sheet)
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaC9mIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f5f116b319ab8cb94812e22a8f9f58f14ced1310/FILE%202023-09-27%2012-37-34.mp4)

**Comment by 2bogd** [comment]
@OlgaSamorodnova did move to Sora repo
