### ISSUE TITLE
iOS - formatting of phone number when it is filled from saved numbers on the device

### ISSUE THREAD

**Issue by OlgaSamorodnova** [sora-xor/sora-card-ios#90]
Steps: fill the phone number with the one saved and proposed by iPhone

Actual result: wrong phone number format
Expected result: let's format such numbers and remove extra symbols

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFhnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--122f8c71b08b17a61a3e65f09c6e3e531252ca45/IMAGE%202023-09-27%2015-23-21.jpg)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGJnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--053cd81aa96b31eb9564da5e41c6a6395d6df7d7/IMAGE%202023-09-27%2015-23-26.jpg)

**Comment by OlgaSamorodnova** [comment]
Now I see a phone number proposal only after I type 1 number and then erase it
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUhnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--93f480fbc2ade96f807c64d7d4066e940df4ac9c/IMG_9099.MP4)

**Comment by OlgaSamorodnova** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWJnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--84410ef06b8e33e0f28aae47959df367a88a04a0/IMG_9099%20%281%29.MP4)

**Comment by bgodlin** [comment]
@OlgaSamorodnova not relevant anymore since the mobile phone UI was changed as part of https://github.com/sora-xor/sora-card/issues/100
