### ISSUE TITLE
[Bug]: Bad UX for user when he tries swipe down the Card Hub screen

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-ios#92]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUQyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--73eae666a659fe87165525b1fbdad11e4613441e/Simulator_Screen_Recording_iPhone_14_Pro_Max_2023_10_02_at_13_30.mp4)

### Preconditions

User passed kyc and has successful status

### Steps to reproduce

1. Open Card hub screen
2. Swipe down the screen to close it

### Actual behavior

User still sees the Card hub screen

### Expected behavior

User can swipe it down for the any part of the screen

### Environment

{"label"=>"Development"}

### OS version

iOS

**Comment by ra9mls** [comment]
@Tieumsan please check on your device. My device:
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1Y4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--791fefadd334fa4e089360e45d3ba82f153229c8/RPReplay_Final1698425530.MP4)

**Comment by Trezeguet1** [comment]
Tested on version 10.
The issue is no longer reproduced.
iOS 16.2 and iPhone 11


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTk5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e870477a56cf3b94ec9b13b58e19b5aed669c539/IMG_1003.MP4)
