### ISSUE TITLE
Phone number format normalisation

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card-ios#99]

**Comment by 2bogd** [comment]
build https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/job/3.6.0/3/

**Comment by 2bogd** [comment]
build with hardcoded api version 2.2.0 
https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/job/3.6.0/5/console

**Comment by 2bogd** [comment]
major / minor UI already implemented

**Comment by ra9mls** [comment]
Waiting the patch implementation

**Comment by Trezeguet1** [comment]
Verified on 3.6.0 (7) version.

![telegram-cloud-photo-size-2-5321414181838245245-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/da98e929-9993-4f4c-b0e5-3d2d31cbc73f)

**Comment by Trezeguet1** [comment]
The country code is entered correctly in accordance with the selected country.
